# Generated by Django 5.0.3 on 2024-11-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_after_dis',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
